Repository aagarwal1012/Animated-Text-Kit, pull requests merged in 2021-03, with the labels that each got.

#204 docs: added pub.green badges to Readme
  README.md
Labels: documentation

#203 added customisable fade in and fade out timings
  lib/src/fade.dart
Labels: GSSOC21, enhancement, level2

#205 docs: fine-tune pub.green links
  README.md
Labels: documentation

#216 Deprecate kits
  README.md
  example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  example/lib/main.dart
  lib/src/colorize.dart
  lib/src/fade.dart
  lib/src/rotate.dart
  lib/src/scale.dart
  lib/src/typer.dart
  lib/src/typewriter.dart
  lib/src/wavy.dart
  test/smoke_test.dart
Labels: deprecation

#217 textStyle property is no longer required for AnimatedText subclasses.
  CHANGELOG.md
  README.md
  example/lib/main.dart
  lib/src/animated_text.dart
  lib/src/colorize.dart
  lib/src/fade.dart
  lib/src/rotate.dart
  lib/src/scale.dart
  lib/src/typer.dart
  lib/src/typewriter.dart
  lib/src/wavy.dart
  pubspec.yaml
Labels: enhancement

#222 [feat] Prepare animated text kit flutter web app for demo
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-prod.yml
  README.md
  example/.firebaserc
  example/.gitignore
  example/android/app/src/main/res/drawable-v21/launch_background.xml
  example/android/app/src/main/res/values-night/styles.xml
  example/firebase.json
  example/lib/main.dart
  example/web/favicon.png
  example/web/icons/Icon-192.png
  example/web/icons/Icon-512.png
  example/web/index.html
  example/web/manifest.json
Labels: documentation, enhancement
